# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered')),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
    ]
