# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_allowed_to_add_post', models.BooleanField(default=False)),
                ('is_allowed_to_edit_post', models.BooleanField(default=False)),
                ('is_allowed_to_drop_post', models.BooleanField(default=False)),
                ('is_allowed_to_add_mod', models.BooleanField(default=False)),
                ('is_allowed_to_manage', models.BooleanField(default=False)),
                ('is_allowed_to_stat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=128)),
                ('date', models.DateTimeField(verbose_name='date registered')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
