# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('news', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
    ]
