# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_allowed_to_add_post', models.BooleanField(default=False)),
                ('is_allowed_to_edit_post', models.BooleanField(default=False)),
                ('is_allowed_to_drop_post', models.BooleanField(default=False)),
                ('is_allowed_to_add_mod', models.BooleanField(default=False)),
                ('is_allowed_to_manage', models.BooleanField(default=False)),
                ('is_allowed_to_stat', models.BooleanField(default=False)),
            ],
        ),
    ]
